[build]
  command = "npm run build"
  publish = "dist/untitled/browser"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[plugins]]
  package = "@netlify/angular-runtime"
